import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/Header";
import { usePathname } from "next/navigation";
import { HeaderWrapper } from "@/components/HeaderWrapper";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebra";
import { cookies } from "next/headers";


export const metadata: Metadata = {
  title: "Lunar Note",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <HeaderWrapper>
            {children}
          </HeaderWrapper>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}

